# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'myagent'

variables:
  node_version: '20.x'
  frontend_path: 'frontend'
  backend_path: 'backend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'backend'
  displayName: 'Installing modules in backend'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'frontend'
  displayName: 'Installing modules in frontend'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'run build'
  displayName: 'Build modules in frontend'

- script: |
    mkdir -p backend/public
    cp -r frontend/build/* backend/public/
  displayName: 'Copy React build to backend/public'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(backend_path)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive app for deployment'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
  displayName: 'Publish build artifact'